edition = "2023";

import "google/api/field_behavior.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

package auth;

option go_package = "github.com/podumai/authentication_service/internal/api/grpc/auth";

// UserCredentials Transfer information for user validation
message UserCredentials {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      title: "UserCredentials"
      description: "Transfer information for user validation"
      required: [
        "email",
        "password"
      ]
    }
    example: "{\"email\": \"user@example.com\", \"password\": \"password\"}"
  };

  string email = 1 [
    json_name = "email",
    (google.api.field_behavior) = REQUIRED,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      title: "email"
      description: "Email address for user validation"
      required: "true"
      format: "string"
      pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
      example: "\"user@example.com\""
    }
  ];

  string password = 2 [
    json_name = "password",
    (google.api.field_behavior) = REQUIRED,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      title: "password"
      description: "Password for user validation"
      required: "true"
      format: "string"
      pattern: ".+"
      example: "\"password\""
    }
  ];
}