// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/token_pair.proto

package auth

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenPair Transfer information about access/refresh token pair
type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *string                `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
	RefreshToken  *string                `protobuf:"bytes,2,opt,name=refresh_token" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_auth_token_pair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_auth_token_pair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_auth_token_pair_proto_rawDescGZIP(), []int{0}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil && x.RefreshToken != nil {
		return *x.RefreshToken
	}
	return ""
}

var File_auth_token_pair_proto protoreflect.FileDescriptor

const file_auth_token_pair_proto_rawDesc = "" +
	"\n" +
	"\x15auth/token_pair.proto\x12\x04auth\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc4\b\n" +
	"\tTokenPair\x12\x8e\x03\n" +
	"\faccess_token\x18\x01 \x01(\tB\xe9\x02\x92A\xe2\x02*\faccess_token2 Access token for user validationJ\xf1\x01\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtcyI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwic3ViIjoiMSIsImF1ZCI6WyJhaS1hc3Npc3RhbnQtYXBwIl0sImV4cCI6MTc3MjIyMTM1NSwiaWF0IjoxNzcyMjIwNDU1fQ.sLKvwgrPluAY-WPeRCHdaqfL65C5rXEPT3V2WEIe-Io\"\x8a\x01+[a-zA-Z0-9-]+\\.[a-zA-Z0-9-]+\\.[a-zA-Z0-9-]+\xd2\x01\x04true\xa2\x02\x06string\xe0A\x02R\faccess_token\x12\xfd\x01\n" +
	"\rrefresh_token\x18\x02 \x01(\tB\xd6\x01\x92A\xcf\x01*\rrefresh_token2>Refresh token for generating new pair of access/refresh tokensJ&\"4e4edca8-7d29-4080-b126-3133607138e6\"\x8a\x01E^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$\xd2\x01\x04true\xa2\x02\x06string\xe0A\x02R\rrefresh_token:\xa5\x03\x92A\xa1\x03\n" +
	"`*\tTokenPair24Transfer information about access/refresh token pair\xd2\x01\faccess_token\xd2\x01\rrefresh_token2\xbc\x02{\"access_token\": \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtcyI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwic3ViIjoiMSIsImF1ZCI6WyJhaS1hc3Npc3RhbnQtYXBwIl0sImV4cCI6MTc3MjIyMTM1NSwiaWF0IjoxNzcyMjIwNDU1fQ.sLKvwgrPluAY-WPeRCHdaqfL65C5rXEPT3V2WEIe-Io\", \"refresh_token\": \"4e4edca8-7d29-4080-b126-3133607138e6\"}BBZ@github.com/podumai/authentication_service/internal/api/grpc/authb\beditionsp\xe8\a"

var (
	file_auth_token_pair_proto_rawDescOnce sync.Once
	file_auth_token_pair_proto_rawDescData []byte
)

func file_auth_token_pair_proto_rawDescGZIP() []byte {
	file_auth_token_pair_proto_rawDescOnce.Do(func() {
		file_auth_token_pair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_token_pair_proto_rawDesc), len(file_auth_token_pair_proto_rawDesc)))
	})
	return file_auth_token_pair_proto_rawDescData
}

var file_auth_token_pair_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_token_pair_proto_goTypes = []any{
	(*TokenPair)(nil), // 0: auth.TokenPair
}
var file_auth_token_pair_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_token_pair_proto_init() }
func file_auth_token_pair_proto_init() {
	if File_auth_token_pair_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_token_pair_proto_rawDesc), len(file_auth_token_pair_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_token_pair_proto_goTypes,
		DependencyIndexes: file_auth_token_pair_proto_depIdxs,
		MessageInfos:      file_auth_token_pair_proto_msgTypes,
	}.Build()
	File_auth_token_pair_proto = out.File
	file_auth_token_pair_proto_goTypes = nil
	file_auth_token_pair_proto_depIdxs = nil
}
