// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/auth.proto

package auth

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bauth/user_credentials.proto\x1a\x15auth/token_pair.proto2\xfb\x05\n" +
	"\x04Auth\x12\xd4\x01\n" +
	"\x05Login\x12\x15.auth.UserCredentials\x1a\x0f.auth.TokenPair\"\xa2\x01\x92A\x8d\x01\n" +
	"\x04Auth\x12!Authenticates and authorizes user\x1abInvolves the process of authentication and authorization with further access/refresh token respond\x82\xd3\xe4\x93\x02\v\"\t/v1/login\x12\x8c\x01\n" +
	"\bRegister\x12\x15.auth.UserCredentials\x1a\x16.google.protobuf.Empty\"Q\x92A:\n" +
	"\x04Auth\x12\x12Registers new user\x1a\x1eCreates new user if not exists\x82\xd3\xe4\x93\x02\x0e\"\f/v1/register\x12\x9c\x01\n" +
	"\aRefresh\x12\x0f.auth.TokenPair\x1a\x0f.auth.TokenPair\"o\x92AY\n" +
	"\x04Auth\x12\x15Create new token pair\x1a:Validates given access/refresh token pair and produces new\x82\xd3\xe4\x93\x02\r\"\v/v1/refresh\x12\xab\x01\n" +
	"\x0eChangePassword\x12\x15.auth.UserCredentials\x1a\x16.google.protobuf.Empty\"j\x92AN\n" +
	"\x04Auth\x12\x18Change password for user\x1a,Provides the ability to change user password\x82\xd3\xe4\x93\x02\x13\"\x11/v1/user/password\x1a@\x92A=\n" +
	"\x04Auth\x125Internal service for authentication and authorizationB\xbe\x02\x92A\xf8\x01\x12\x8e\x01\n" +
	"\x1aAuthentication Service API\"&\n" +
	"\x0eKirill Morozov\x1a\x14kirillsm05@gmail.com*A\n" +
	"\x12Apache License 2.0\x12+https://www.apache.org/licenses/LICENSE-2.02\x051.0.0*\x02\x01\x022\x10application/json:\x10application/jsonj=\n" +
	"\x04Auth\x125Internal service for authentication and authorizationZ@github.com/podumai/authentication_service/internal/api/grpc/authb\beditionsp\xe8\a"

var file_auth_auth_proto_goTypes = []any{
	(*UserCredentials)(nil), // 0: auth.UserCredentials
	(*TokenPair)(nil),       // 1: auth.TokenPair
	(*emptypb.Empty)(nil),   // 2: google.protobuf.Empty
}
var file_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.Auth.Login:input_type -> auth.UserCredentials
	0, // 1: auth.Auth.Register:input_type -> auth.UserCredentials
	1, // 2: auth.Auth.Refresh:input_type -> auth.TokenPair
	0, // 3: auth.Auth.ChangePassword:input_type -> auth.UserCredentials
	1, // 4: auth.Auth.Login:output_type -> auth.TokenPair
	2, // 5: auth.Auth.Register:output_type -> google.protobuf.Empty
	1, // 6: auth.Auth.Refresh:output_type -> auth.TokenPair
	2, // 7: auth.Auth.ChangePassword:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	file_auth_user_credentials_proto_init()
	file_auth_token_pair_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
