// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/user_credentials.proto

package auth

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserCredentials Transfer information for user validation
type UserCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCredentials) Reset() {
	*x = UserCredentials{}
	mi := &file_auth_user_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredentials) ProtoMessage() {}

func (x *UserCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredentials.ProtoReflect.Descriptor instead.
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return file_auth_user_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *UserCredentials) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserCredentials) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

var File_auth_user_credentials_proto protoreflect.FileDescriptor

const file_auth_user_credentials_proto_rawDesc = "" +
	"\n" +
	"\x1bauth/user_credentials.proto\x12\x04auth\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xae\x03\n" +
	"\x0fUserCredentials\x12\x9f\x01\n" +
	"\x05email\x18\x01 \x01(\tB\x88\x01\x92A\x81\x01*\x05email2!Email address for user validationJ\x12\"user@example.com\"\x8a\x010^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\xd2\x01\x04true\xa2\x02\x06string\xe0A\x02R\x05email\x12k\n" +
	"\bpassword\x18\x02 \x01(\tBO\x92AI*\bpassword2\x1cPassword for user validationJ\n" +
	"\"password\"\x8a\x01\x02.+\xd2\x01\x04true\xa2\x02\x06string\xe0A\x02R\bpassword:\x8b\x01\x92A\x87\x01\n" +
	"N*\x0fUserCredentials2(Transfer information for user validation\xd2\x01\x05email\xd2\x01\bpassword25{\"email\": \"user@example.com\", \"password\": \"password\"}BBZ@github.com/podumai/authentication_service/internal/api/grpc/authb\beditionsp\xe8\a"

var (
	file_auth_user_credentials_proto_rawDescOnce sync.Once
	file_auth_user_credentials_proto_rawDescData []byte
)

func file_auth_user_credentials_proto_rawDescGZIP() []byte {
	file_auth_user_credentials_proto_rawDescOnce.Do(func() {
		file_auth_user_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_user_credentials_proto_rawDesc), len(file_auth_user_credentials_proto_rawDesc)))
	})
	return file_auth_user_credentials_proto_rawDescData
}

var file_auth_user_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_user_credentials_proto_goTypes = []any{
	(*UserCredentials)(nil), // 0: auth.UserCredentials
}
var file_auth_user_credentials_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_user_credentials_proto_init() }
func file_auth_user_credentials_proto_init() {
	if File_auth_user_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_user_credentials_proto_rawDesc), len(file_auth_user_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_user_credentials_proto_goTypes,
		DependencyIndexes: file_auth_user_credentials_proto_depIdxs,
		MessageInfos:      file_auth_user_credentials_proto_msgTypes,
	}.Build()
	File_auth_user_credentials_proto = out.File
	file_auth_user_credentials_proto_goTypes = nil
	file_auth_user_credentials_proto_depIdxs = nil
}
